### ISSUE TITLE
Error message during execution on a laptop

### ISSUE THREAD

**Issue by yossimr** [TonyPhipps/Meerkat#1]
Hello,

I have followed the requirements as described in the project, however i am getting the following error while  executing the command in power shell in admin mode on my laptop.

[DESKTOP-XXX] Connecting to remote server DESKTOP-XXX failed with the following error message : The client
cannot connect to the destination specified in the request. Verify that the service on the destination is running and
is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination,
most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to
analyze and configure the WinRM service: "winrm quickconfig". For more information, see the
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (DESKTOP-XXX:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : CannotConnect,PSSessionStateBroken

Also there are no output files generated in the tmp dir.

Help is appreciated.

Regards

Yossi

**Comment by TonyPhipps** [comment]
You'll likely need to enable winrm, as specified in the error. try this

`PsExec.exe -s \\$TargetComputer -accepteula powershell -ExecutionPolicy ByPass -nologo -command "Enable-PSRemoting -Force"`

... where $TargetComputer is your target 

another option is using "winrm quickconfig"

I'll look into adding this into the tool directly OR partially removing WinRM dependencies (e.g. no WinRM requirement when called via the psexec module)

**Comment by TonyPhipps** [comment]
I've found a way to remove the WinRM requirement when doing a local collection or using the psexec wrapper. Will be reflected in next major update.

**Comment by TonyPhipps** [comment]
All modules were adjusted to no longer require WinRM when either scanning the local system OR using the psexec wrapper Invoke-THR_PSExec

**Comment by yossimr** [comment]
Hi,

Thank you for your efforts 

I will try the new build. 

Regards 

Yossi

**Comment by yossimr** [comment]
Hi,

I have tried the new build and it works fine :)

Thanks a lot

Yossi

**Comment by zwass** [comment]
I see similar errors when running Meerkat from `master`. Is there a flag or something to enable for this fix?

**Comment by TonyPhipps** [comment]
zwass,
One of the core requirements of remoting with Meerkat is that WinRM be enabled and the endpoint (if remote) be reachable. There is one alternative provided in the psexec wrapper, mentioned above.

If you want to post the command and error I'll be able to see if it's this issue or another.

**Comment by zwass** [comment]
Ah, I didn't realize that Meerkat was attempting to reach out to remote machines. Is it possible to run it to just collect the results on the local machine? Could this be done without enabling WinRM?

**Comment by TonyPhipps** [comment]
If you run the command below it will run locally using Invoke-Command, so it's subject to all invoke-command requirements, which includes WinRM. If you're getting an error, please send it up and I'll take a look.
`Invoke-Meerkat`

Optionally, you can run the modules directly and bypass Invoke-Command
`get-computerdetails | export-csv c:\temp.csv -NoTypeInformation `

I will look into making something like Invoke-Meerkat-Local that completely drops the Invoke-Command dependency.

To resolve your issue, you can set up winrm on your system as outlined above or here
https://github.com/TonyPhipps/Powershell/blob/master/Enable-WinRM.ps1

**Comment by TonyPhipps** [comment]
https://github.com/TonyPhipps/Meerkat/projects/1#card-31127749
